import Foundation
import Connect
import MLoggerKit

// MARK: - ConnectRPC Client Configuration

/// Configuration for creating ConnectRPC clients through CoreNetworkKit.
///
/// v2: Uses an `InterceptorChain` for authentication and header injection
/// instead of directly accepting `tokenStorage` / `authStrategy`.
///
/// ```swift
/// let config = ConnectClientConfig(
///     host: "https://api.example.com",
///     engine: alamofireEngine,
///     chain: sharedInterceptorChain
/// )
/// ```
public struct ConnectClientConfig {

    /// The host URL for the ConnectRPC service (e.g. "https://api.example.com").
    public let host: String

    /// The underlying network engine used for HTTP transport.
    public let engine: NetworkEngine

    /// Interceptor chain shared with `NetworkClientV2`. Handles token
    /// injection, tracing, negotiation, etc. for ConnectRPC calls.
    public let chain: InterceptorChain?

    /// The wire protocol to use. Defaults to `.connect`.
    public let networkProtocol: NetworkProtocol

    /// The codec for serialization/deserialization. Defaults to `ProtoCodec()`.
    public let codec: Codec

    /// Interceptor factories for request/response transformation (connect-swift level).
    public let interceptors: [InterceptorFactory]

    /// Request-level timeout (applied by connect-swift). `nil` means no timeout.
    public let timeout: TimeInterval?

    /// v2 initializer using interceptor chain.
    public init(
        host: String,
        engine: NetworkEngine,
        chain: InterceptorChain? = nil,
        networkProtocol: NetworkProtocol = .connect,
        codec: Codec = ProtoCodec(),
        interceptors: [InterceptorFactory] = [],
        timeout: TimeInterval? = nil
    ) {
        self.host = host
        self.engine = engine
        self.chain = chain
        self.networkProtocol = networkProtocol
        self.codec = codec
        self.interceptors = interceptors
        self.timeout = timeout
    }

    /// Legacy initializer preserved for backward compatibility.
    @available(*, deprecated, message: "Use init(host:engine:chain:...) instead")
    public init(
        host: String,
        engine: NetworkEngine,
        tokenStorage: TokenStorage,
        tokenRefresher: TokenRefresher? = nil,
        authStrategy: AuthenticationStrategy = BearerTokenAuthenticationStrategy(),
        networkProtocol: NetworkProtocol = .connect,
        codec: Codec = ProtoCodec(),
        interceptors: [InterceptorFactory] = [],
        timeout: TimeInterval? = nil
    ) {
        self.host = host
        self.engine = engine
        let compatChain = InterceptorChain()
        compatChain.use(LegacyConnectAuthInterceptor(
            tokenStorage: tokenStorage,
            authStrategy: authStrategy
        ))
        self.chain = compatChain
        self.networkProtocol = networkProtocol
        self.codec = codec
        self.interceptors = interceptors
        self.timeout = timeout
    }
}

// MARK: - ConnectRPC Client Factory

/// Factory for creating typed ConnectRPC clients backed by CoreNetworkKit.
///
/// Provides a centralized entry point for constructing `ProtocolClient` instances
/// that reuse CoreNetworkKit's HTTP engine, MTLS, and authentication strategies.
///
/// ```swift
/// let factory = ConnectClientFactory(config: connectConfig)
///
/// // Create a typed service client (generated by protoc-gen-connect-swift)
/// let eliza = factory.makeClient(ElizaServiceClient.self)
/// let response = try await eliza.say(request: .with { $0.sentence = "Hi" })
/// ```
public final class ConnectClientFactory {

    // MARK: - Properties

    private let config: ConnectClientConfig
    private let transport: ConnectTransport
    private let protocolClient: ProtocolClient
    private let logger = LoggerFactory.network

    // MARK: - Initialization

    /// Create a factory with the given configuration.
    ///
    /// - Parameter config: ConnectRPC client configuration.
    public init(config: ConnectClientConfig) {
        self.config = config
        self.transport = ConnectTransport(
            engine: config.engine,
            chain: config.chain
        )

        let protocolConfig = ProtocolClientConfig(
            host: config.host,
            networkProtocol: config.networkProtocol,
            codec: config.codec,
            interceptors: config.interceptors,
            timeout: config.timeout
        )

        self.protocolClient = ProtocolClient(
            httpClient: transport,
            config: protocolConfig
        )

        logger.debug(
            "[ConnectClientFactory] Initialized for host: \(config.host)",
            tag: "connect"
        )
    }

    // MARK: - Client Creation

    /// Create a typed ConnectRPC service client.
    ///
    /// The `ServiceClient` type is typically generated by `protoc-gen-connect-swift`
    /// and has an `init(client: ProtocolClientInterface)` constructor.
    ///
    /// ```swift
    /// let eliza = factory.makeClient(ElizaServiceClient.self)
    /// ```
    ///
    /// - Parameter serviceType: The generated service client type.
    /// - Returns: A configured service client instance.
    public func makeClient<T: ConnectServiceClient>(_ serviceType: T.Type) -> T {
        return serviceType.init(client: protocolClient)
    }

    /// Access the underlying `ProtocolClientInterface` directly.
    ///
    /// Useful for advanced scenarios where callers need to invoke RPCs
    /// without a generated service client.
    public var client: ProtocolClientInterface {
        return protocolClient
    }
}

// MARK: - Service Client Protocol

/// Protocol that generated ConnectRPC service clients conform to.
///
/// All service clients generated by `protoc-gen-connect-swift` have an
/// `init(client: ProtocolClientInterface)` constructor. This protocol
/// captures that pattern so the factory can instantiate them generically.
///
/// To conform a generated client:
/// ```swift
/// extension ElizaServiceClient: ConnectServiceClient {}
/// ```
public protocol ConnectServiceClient {
    /// Create the service client with a protocol client.
    init(client: ProtocolClientInterface)
}

// MARK: - Convenience Extension on NetworkClient

extension NetworkClient {

    /// Create a `ConnectClientFactory` that shares this client's engine.
    ///
    /// This is a convenience method for creating ConnectRPC clients that reuse
    /// the same networking stack as the existing `NetworkClient`.
    ///
    /// ```swift
    /// let factory = networkClient.connectFactory(host: "https://grpc.example.com")
    /// let service = factory.makeClient(MyServiceClient.self)
    /// ```
    ///
    /// - Parameters:
    ///   - host: Service host URL.
    ///   - chain: Optional interceptor chain. Pass the v2 chain for shared auth.
    ///   - networkProtocol: Wire protocol. Defaults to `.connect`.
    ///   - codec: Serialization codec. Defaults to `ProtoCodec()`.
    ///   - interceptors: Interceptor factories. Defaults to empty.
    ///   - timeout: Request timeout. Defaults to `nil`.
    /// - Returns: A configured `ConnectClientFactory`.
    public func connectFactory(
        host: String,
        chain: InterceptorChain? = nil,
        networkProtocol: NetworkProtocol = .connect,
        codec: Codec = ProtoCodec(),
        interceptors: [InterceptorFactory] = [],
        timeout: TimeInterval? = nil
    ) -> ConnectClientFactory {
        return ConnectClientFactory(config: ConnectClientConfig(
            host: host,
            engine: _engine,
            chain: chain,
            networkProtocol: networkProtocol,
            codec: codec,
            interceptors: interceptors,
            timeout: timeout
        ))
    }
}

// MARK: - Legacy Auth Interceptor for ConnectClientFactory

private struct LegacyConnectAuthInterceptor: RequestInterceptor, @unchecked Sendable {
    let tokenStorage: TokenStorage
    let authStrategy: AuthenticationStrategy

    func onRequest(_ config: RequestConfig) async throws -> RequestConfig {
        guard let url = URL(string: config.url) else { return config }
        var urlRequest = URLRequest(url: url)
        for (key, value) in config.headers {
            urlRequest.setValue(value, forHTTPHeaderField: key)
        }

        let context = AuthenticationContext(tokenStorage: tokenStorage)
        let authed = try await authStrategy.apply(to: urlRequest, context: context)

        var updated = config
        if let allHeaders = authed.allHTTPHeaderFields {
            for (key, value) in allHeaders {
                updated.headers[key] = value
            }
        }
        return updated
    }
}
